services:
  control-plane:
    build:
      context: .
      dockerfile: Dockerfile.control-plane
    container_name: control-plane
    ports:
      - "18000:18000"  # gRPC port for CLI management
      - "8734:8734"    # HTTP port for cache display web interface
    networks:
      envoy-net:
        ipv4_address: 172.20.0.10

  envoy:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy
    ports:
      - "10000:10000"  # Main proxy port
      - "10001:10001"  # Additional proxy port
      - "10002:10002"  # Additional proxy port  
      - "10003:10003"  # Additional proxy port
      - "60001:60001"  # Admin interface
    volumes:
      - ./envoy/bootstrap-docker.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      envoy-net:
        ipv4_address: 172.20.0.20
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]

  test-servers:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-servers
    command: ["./test-server", "-config", "config.json"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.30
    ports:
      - "50051:50051"  # Main gRPC server
      - "50052:50052"  # HTTP server
      - "50053:50053"  # Dynamic gRPC server 1
      - "50054:50054"  # Dynamic gRPC server 2

  # Additional standalone servers for outlier detection testing
  test-server-grpc-4:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-4
    command: ["./test-server", "-config", "config-grpc-4.json"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.34
    ports:
      - "50055:50055"

  # This server always returns 500 errors for outlier detection testing
  test-server-grpc-failing:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-failing
    command: ["./test-server", "-config", "config-grpc-failing.json"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.35
    ports:
      - "50056:50056"

  # Debug container with network tools
  debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: debug
    networks:
      envoy-net:
        ipv4_address: 172.20.0.100
    tty: true
    stdin_open: true

networks:
  envoy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
