services:
  control-plane:
    build:
      context: .
      dockerfile: Dockerfile.control-plane
    container_name: control-plane
    ports:
      - "18000:18000"  # gRPC port for CLI management
      - "8734:8734"    # HTTP port for cache display web interface
    networks:
      envoy-net:
        ipv4_address: 172.20.0.10

  envoy:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy
    ports:
      - "10000:10000"  # Main proxy port
      - "10001:10001"  # Additional proxy port
      - "10002:10002"  # Additional proxy port  
      - "10003:10003"  # Additional proxy port
      - "60001:60001"  # Admin interface
    volumes:
      - ./envoy/bootstrap-docker.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      envoy-net:
        ipv4_address: 172.20.0.20
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]

  test-server-grpc:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc
    command: ["./test-server", "-port", "50051", "-message", "Docker-gRPC", "-bind-all"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.30

  test-server-http:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-http
    command: ["./test-server-http", "-port", "50052", "-message", "Docker-HTTP", "-bind-all"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.31

  # Additional test servers for dynamic testing
  test-server-grpc-2:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-2
    command: ["./test-server", "-port", "50053", "-message", "Docker-gRPC-2", "-bind-all"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.32

  # Additional test servers for outlier detection testing
  test-server-grpc-3:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-3
    command: ["./test-server", "-port", "50054", "-message", "Docker-gRPC-3", "-bind-all"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.33

  test-server-grpc-4:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-4
    command: ["./test-server", "-port", "50055", "-message", "Docker-gRPC-4", "-bind-all"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.34

  # This server always returns 500 errors for outlier detection testing
  test-server-grpc-failing:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    container_name: test-server-grpc-failing
    command: ["./test-server", "-port", "50056", "-message", "Docker-gRPC-Failing", "-bind-all", "-always-fail"]
    networks:
      envoy-net:
        ipv4_address: 172.20.0.35

  # Debug container with network tools
  debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: debug
    networks:
      envoy-net:
        ipv4_address: 172.20.0.100
    tty: true
    stdin_open: true

networks:
  envoy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
